# Generated by Django 4.0.3 on 2022-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_matrixroommodel_useraccountmodel_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixroommodel',
            name='room_id',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
